const CACHE='ekyc-viewer-v10';
const ASSETS=['./','./index.html','./manifest.webmanifest','./sw.js','./icon.svg'];
const UI=`<style id="ekyc-ui">
:root{--bg:#f2f2f7;--surface:#fff;--surface2:#f8f8fa;--text:#111;--muted:#6e6e73;--line:#d1d1d6;--accent:#007aff;--success:#34c759;--danger:#ff3b30}
*{box-sizing:border-box!important}html{-webkit-text-size-adjust:100%;background:var(--bg)!important}body{margin:0!important;min-width:0!important;overflow-x:hidden!important;background:var(--bg)!important;color:var(--text)!important;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Text","Helvetica Neue",sans-serif!important;-webkit-font-smoothing:antialiased!important}
main{width:min(100%,620px)!important;max-width:620px!important;margin:auto!important;padding:calc(env(safe-area-inset-top) + 30px) 18px calc(env(safe-area-inset-bottom) + 46px)!important}
.hero{padding:4px 2px 26px!important}.eyebrow{font-size:12px!important;line-height:1!important;font-weight:700!important;letter-spacing:.9px!important;color:var(--accent)!important;margin:0 0 10px!important}.hero h1{font-size:44px!important;line-height:.98!important;letter-spacing:-2.4px!important;margin:0 0 12px!important;font-weight:750!important}.hero .muted{font-size:17px!important;line-height:1.45!important;max-width:540px!important;margin:0!important}.muted{color:var(--muted)!important;line-height:1.45!important}
.privacy{background:var(--surface)!important;border:1px solid var(--line)!important;border-radius:22px!important;padding:18px!important;margin-bottom:14px!important;box-shadow:none!important}.privacy b{display:block!important;font-size:18px!important;line-height:1.2!important;margin-bottom:6px!important}.privacy>.muted{font-size:15px!important;line-height:1.42!important}.privacy .pill{display:flex!important;align-items:center!important;gap:7px!important;color:var(--success)!important;font-size:13px!important;font-weight:650!important;margin-top:13px!important}.privacy .pill span{font-size:inherit!important;color:inherit!important}.privacy .dot{width:7px!important;height:7px!important;border-radius:50%!important;background:var(--success)!important;flex:none!important}
.actions{display:grid!important;gap:10px!important;margin-top:0!important}.button{appearance:none!important;border:0!important;border-radius:17px!important;min-height:56px!important;padding:15px 18px!important;font-size:17px!important;font-weight:700!important;text-align:center!important;cursor:pointer!important}.primary{background:var(--accent)!important;color:#fff!important}.secondary{background:var(--surface)!important;color:var(--text)!important;border:1px solid var(--line)!important}.button:active{transform:scale(.99)!important;opacity:.9!important}.zip-panel{display:none;margin-top:12px!important;background:var(--surface)!important;border:1px solid var(--line)!important;border-radius:20px!important;padding:15px!important}.zip-panel label{display:block!important;font-size:13px!important;color:var(--muted)!important;margin-bottom:7px!important}.zip-panel input{display:block!important;width:100%!important;border:1px solid var(--line)!important;background:var(--surface2)!important;color:var(--text)!important;border-radius:14px!important;padding:14px 15px!important;font-size:17px!important;outline:none!important}.zip-panel .button{width:100%!important;margin-top:10px!important}.status{text-align:center!important;font-size:13px!important;color:var(--muted)!important;min-height:20px!important;margin:12px 2px 2px!important;overflow-wrap:anywhere!important}.status.error{color:var(--danger)!important}.status.success{color:var(--success)!important}
#result{display:none!important}.profile{display:flex!important;gap:17px!important;align-items:center!important;background:var(--surface)!important;border:1px solid var(--line)!important;border-radius:24px!important;padding:16px!important;margin:24px 0 18px!important;box-shadow:none!important}.photo{width:92px!important;height:116px!important;object-fit:cover!important;border-radius:15px!important;border:1px solid var(--line)!important;display:none;background:#eee!important;flex:none!important}.profile h2{margin:0 0 7px!important;font-size:27px!important;line-height:1.05!important;letter-spacing:-.8px!important;font-weight:750!important}.profile p{margin:4px 0!important;color:var(--muted)!important;font-size:15px!important;line-height:1.3!important}
.grid{display:flex!important;flex-direction:column!important;gap:0!important;background:var(--surface)!important;border:1px solid var(--line)!important;border-radius:22px!important;overflow:hidden!important}.field{position:relative!important;min-width:0!important;margin:0!important;padding:17px 18px!important;background:var(--surface)!important;border:0!important;border-bottom:1px solid var(--line)!important;border-radius:0!important;box-shadow:none!important}.field:last-child{border-bottom:0!important}.label{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;text-transform:uppercase!important;letter-spacing:.65px!important;font-size:11px!important;color:var(--muted)!important;margin-bottom:7px!important;font-weight:700!important}.value{font-size:17px!important;line-height:1.45!important;overflow-wrap:anywhere!important;white-space:pre-wrap!important}.value.masked{letter-spacing:2px!important;font-size:16px!important}.field-actions{display:flex!important;gap:8px!important;margin-top:9px!important}.mini{appearance:none!important;border:0!important;background:transparent!important;color:var(--accent)!important;font-size:14px!important;font-weight:600!important;padding:0!important;cursor:pointer!important}.tools{display:grid!important;grid-template-columns:1fr!important;gap:10px!important;margin-top:14px!important}.raw{margin-top:14px!important;background:var(--surface)!important;border:1px solid var(--line)!important;border-radius:20px!important;padding:16px 18px!important}.raw summary{font-size:16px!important;font-weight:650!important;cursor:pointer!important}.raw pre{font-size:12px!important;line-height:1.5!important;white-space:pre-wrap!important;overflow-wrap:anywhere!important;color:var(--muted)!important;margin:14px 0 0!important}.footer{font-size:12px!important;color:var(--muted)!important;line-height:1.55!important;margin:17px 4px 0!important}
@media(max-width:500px){main{padding-left:16px!important;padding-right:16px!important}.hero{padding-bottom:22px!important}.hero h1{font-size:40px!important}.hero .muted{font-size:17px!important}.privacy{padding:17px!important;border-radius:21px!important}.profile{margin-top:22px!important;padding:15px!important;border-radius:22px!important}.profile h2{font-size:25px!important}.photo{width:88px!important;height:112px!important}.grid{border-radius:21px!important}.field{padding:16px!important}.button{min-height:55px!important}}
@media(prefers-color-scheme:dark){:root{--bg:#000;--surface:#1c1c1e;--surface2:#2c2c2e;--text:#f5f5f7;--muted:#98989d;--line:#38383a;--accent:#0a84ff;--success:#30d158;--danger:#ff453a}html,body{background:#000!important}.primary{background:#0a84ff!important}.photo{background:#2c2c2e!important}.zip-panel input{background:#2c2c2e!important;color:#fff!important}}
</style>`;
async function styleHTML(response){if(!response||!response.ok)return response;const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();if(!html.includes('id="ekyc-ui"'))html=html.replace('</head>',UI+'</head>');return new Response(html,{status:response.status,statusText:response.statusText,headers:{'Content-Type':'text/html;charset=UTF-8','Cache-Control':'no-store'}})}
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==self.location.origin)return;event.respondWith(fetch(event.request).then(r=>{if(r.ok)caches.open(CACHE).then(c=>c.put(event.request,r.clone())).catch(()=>{});return styleHTML(r)}).catch(()=>caches.match(event.request).then(r=>r?styleHTML(r):new Response('Offline',{status:503}))))});
